### ISSUE TITLE
一点建议（

### ISSUE THREAD

**Issue by Haocen2004** [limbang/mirai-console-minecraft-plugin#1]
让查询指令也支持一下私聊环境（指 !list 这些）
修改查询指令为 !ping <serverName> 感觉这样会更符合直觉（
同理 !tps <serverName>
增加单次查询指令  !ping <ip> [port] 
增加批量查询 !pingall
个人一点小小看法 不喜欢请直接close这个issue

**Comment by limbang** [comment]
不支持私聊,是考虑到多群同一个机器人,机器人在不同的群可以有不同的服务器,如果从群发起对话还是可以识别到群的
!list 只是查看服务器列表的
可以加个批量查询的!all

**Comment by limbang** [comment]
!ping !tps 我去做个调查看看都习惯哪种

**Comment by limbang** [comment]
下次更新做自定义命令

**Comment by Haocen2004** [comment]
emm我的意思是可以增加临时ping指令
例如!ping hypixel.net 
（我群的实际使用环境是有时候群员会分享一个服务器 只会ping一次展示一下 每次都要添加->ping->删除
------------ 
对于不同群有不同服务器这点，不是很理解，至少目前添加的服务器列表是跨群的（多个群都是一个list）
------------
以及补充几个建议
- 添加服务器时的 port 能不能改为可选参数 默认25565
- 在添服务器时候加个参数标识是否在ping的时候包括服务器地址
------------
可惜现在手上没有设备整开发环境不然一个pr过来加描述最清楚

**Comment by limbang** [comment]
> ## emm我的意思是可以增加临时ping指令
> 例如!ping hypixel.net
> （我群的实际使用环境是有时候群员会分享一个服务器 只会ping一次展示一下 每次都要添加->ping->删除
> ## 对于不同群有不同服务器这点，不是很理解，至少目前添加的服务器列表是跨群的（多个群都是一个list）
> 以及补充几个建议
> 
> * 添加服务器时的 port 能不能改为可选参数 默认25565
> * 在添服务器时候加个参数标识是否在ping的时候包括服务器地址
> 
> 可惜现在手上没有设备整开发环境不然一个pr过来加描述最清楚

跨群应该bug 原版做的是不跨群的  添加临时ping 懂了 和 默认端口

**Comment by limbang** [comment]
> ## emm我的意思是可以增加临时ping指令
> 例如!ping hypixel.net
> （我群的实际使用环境是有时候群员会分享一个服务器 只会ping一次展示一下 每次都要添加->ping->删除
> ## 对于不同群有不同服务器这点，不是很理解，至少目前添加的服务器列表是跨群的（多个群都是一个list）
> 以及补充几个建议
> 
> * 添加服务器时的 port 能不能改为可选参数 默认25565
> * 在添服务器时候加个参数标识是否在ping的时候包括服务器地址
> 
> 可惜现在手上没有设备整开发环境不然一个pr过来加描述最清楚

在添服务器时候加个参数标识是否在ping的时候包括服务器地址。 这句话是啥意思？不是很明白

**Comment by Haocen2004** [comment]
就是发送消息时候是否包括服务器地址
e.g：
服务器xxx
ip：hypixel.net
motd：xxx
（群里之前来了个新人在那边学着别人ping服务器 但不知道有！list 搁哪一边问地址是什么一边一直ping服务器

**Comment by limbang** [comment]
> 就是发送消息时候是否包括服务器地址
> e.g：
> 服务器xxx
> ip：hypixel.net
> motd：xxx
> （群里之前来了个新人在那边学着别人ping服务器 但不知道有！list 搁哪一边问地址是什么一边一直ping服务器

建议直接戳一戳机器人有帮助 或者看有空了能不能做成自定义
